server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
#      routes:
#        - id: payment-routh #payment_route
#          uri: http://localhost:8001
#          predicates:
#            - Path=/payment/get/**
#
#        - id: payment-routh2
#          uri: http://localhost:8001
#          predicates:
#            - Path=/payment/lb/**
      routes:
        - id: payment-routh #payment_route
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**

        - id: payment-routh2
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
      discovery:
        locator:
          enabled: true

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
