server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Craaab/spring-config.git
          search-paths:
            - spring-config
      label: master

eureka:
  client:
#    register-with-eureka: true
#    fetch-registry: true
    service-url:
      #      defaultZone: "http://localhost:7001/eureka"
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka